buy_me_a_coffee: pboling
github: [pboling] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
issuehunt: pboling # Replace with a single IssueHunt username
ko_fi: pboling # Replace with a single Ko-fi username
liberapay: pboling # Replace with a single Liberapay username
open_collective: galtzo-floss
patreon: galtzo # Replace with a single Patreon username
polar: pboling
thanks_dev: u/gh/pboling
